
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Apr  7 2023 20:13:44 IST (Apr  7 2023 14:43:44 UTC)

// Verification Directory fv/FIFO 

module FIFO(wr_en, rd_en, rst_n, clk, data_in, data_out, status_full,
     status_empty, half_full);
  input wr_en, rd_en, rst_n, clk;
  input [7:0] data_in;
  output [7:0] data_out;
  output status_full, status_empty, half_full;
  wire wr_en, rd_en, rst_n, clk;
  wire [7:0] data_in;
  wire [7:0] data_out;
  wire status_full, status_empty, half_full;
  wire [7:0] \FIFO[2] ;
  wire [7:0] \FIFO[0] ;
  wire [7:0] \FIFO[1] ;
  wire [7:0] \FIFO[3] ;
  wire [2:0] count;
  wire [1:0] wr_pointer;
  wire [1:0] rd_pointer;
  wire UNCONNECTED, \data_out[0]_361 , \data_out[0]_369 ,
       \data_out[1]_362 , \data_out[2]_363 , \data_out[3]_364 ,
       \data_out[4]_365 , \data_out[5]_366 ;
  wire \data_out[6]_367 , \data_out[7]_368 , n_0, n_1, n_2, n_3, n_5,
       n_6;
  wire n_8, n_9, n_12, n_13, n_15, n_16, n_17, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_28, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_36, n_37;
  wire n_39, n_45, n_46, n_47, n_51, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_61, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_72, n_73, n_74;
  wire n_75, n_76, n_77, n_78, n_79, n_80, n_81, n_82;
  wire n_83, n_84, n_85, n_86, n_87, n_88, n_90, n_91;
  wire n_92, n_93, n_94, n_95, n_96, n_97, n_98, n_99;
  wire n_100, n_101, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_111, n_112, n_113, n_114, n_115, n_116;
  wire n_117, n_118, n_119, n_120, n_121, n_122, n_123, n_124;
  wire n_125, n_126, n_127, n_128, n_129, n_130, n_131, n_132;
  wire n_133, n_134, n_135, n_136, n_137, n_138, n_144, n_149;
  wire n_151, n_154, n_155, n_157, n_161, n_165, n_166, n_167;
  wire n_171, n_172, n_173;
  DFQM1RA \data_out_reg[0] (.CK (clk), .D (n_134), .Q (\data_out[0]_361
       ));
  DFQM1RA \data_out_reg[1] (.CK (clk), .D (n_136), .Q (\data_out[1]_362
       ));
  DFQM1RA \data_out_reg[2] (.CK (clk), .D (n_132), .Q (\data_out[2]_363
       ));
  DFQM1RA \data_out_reg[3] (.CK (clk), .D (n_138), .Q (\data_out[3]_364
       ));
  DFQM1RA \data_out_reg[4] (.CK (clk), .D (n_131), .Q (\data_out[4]_365
       ));
  DFQM1RA \data_out_reg[5] (.CK (clk), .D (n_133), .Q (\data_out[5]_366
       ));
  DFQM1RA \data_out_reg[6] (.CK (clk), .D (n_135), .Q (\data_out[6]_367
       ));
  DFQM1RA \data_out_reg[7] (.CK (clk), .D (n_137), .Q (\data_out[7]_368
       ));
  ND3M2R g7083__2398(.A (n_124), .B (n_108), .C (n_94), .Z (n_138));
  ND3M2R g7087__5107(.A (n_122), .B (n_112), .C (n_90), .Z (n_137));
  ND3M2R g7082__6260(.A (n_127), .B (n_121), .C (n_96), .Z (n_136));
  ND3M2R g7084__4319(.A (n_125), .B (n_109), .C (n_91), .Z (n_135));
  ND3M2R g7081__8428(.A (n_129), .B (n_115), .C (n_99), .Z (n_134));
  ND3M2R g7085__5526(.A (n_126), .B (n_106), .C (n_92), .Z (n_133));
  ND3M2R g7080__6783(.A (n_130), .B (n_111), .C (n_95), .Z (n_132));
  ND3M2R g7086__3680(.A (n_123), .B (n_107), .C (n_100), .Z (n_131));
  AOI21M2R g7090__1617(.A1 (n_128), .A2 (\FIFO[2] [2]), .B (n_104), .Z
       (n_130));
  AOI21M2R g7089__2802(.A1 (n_128), .A2 (\FIFO[2] [0]), .B (n_105), .Z
       (n_129));
  AOI21M2R g7088__1705(.A1 (n_128), .A2 (\FIFO[2] [1]), .B (n_102), .Z
       (n_127));
  AOI21M2R g7092__5122(.A1 (n_128), .A2 (\FIFO[2] [5]), .B (n_119), .Z
       (n_126));
  AOI21M2R g7095__8246(.A1 (n_128), .A2 (\FIFO[2] [6]), .B (n_117), .Z
       (n_125));
  AOI21M2R g7094__7098(.A1 (n_128), .A2 (\FIFO[2] [3]), .B (n_103), .Z
       (n_124));
  AOI21M2R g7093__6131(.A1 (n_128), .A2 (\FIFO[2] [4]), .B (n_120), .Z
       (n_123));
  AOI21M2R g7096__1881(.A1 (n_128), .A2 (\FIFO[2] [7]), .B (n_116), .Z
       (n_122));
  AOI22M2R g7118__5115(.A1 (n_114), .A2 (\FIFO[0] [1]), .B1 (n_113),
       .B2 (\FIFO[1] [1]), .Z (n_121));
  NR2B1M2R g7112__7482(.B (n_118), .NA (\FIFO[3] [4]), .Z (n_120));
  NR2B1M2R g7113__4733(.B (n_118), .NA (\FIFO[3] [5]), .Z (n_119));
  NR2B1M2R g7114__6161(.B (n_118), .NA (\FIFO[3] [6]), .Z (n_117));
  NR2B1M2R g7115__9315(.B (n_118), .NA (\FIFO[3] [7]), .Z (n_116));
  AOI22M2R g7117__9945(.A1 (n_114), .A2 (\FIFO[0] [0]), .B1 (n_113),
       .B2 (\FIFO[1] [0]), .Z (n_115));
  AOI22M2R g7111__2883(.A1 (n_114), .A2 (\FIFO[0] [7]), .B1 (n_113),
       .B2 (\FIFO[1] [7]), .Z (n_112));
  AOI22M2R g7119__2346(.A1 (n_114), .A2 (\FIFO[0] [2]), .B1 (n_113),
       .B2 (\FIFO[1] [2]), .Z (n_111));
  DFMQM2RA \FIFO_reg[2][6] (.CK (clk), .D1 (\FIFO[2] [6]), .D2
       (data_in[6]), .S (n_171), .Q (\FIFO[2] [6]));
  DFMQM2RA \FIFO_reg[2][4] (.CK (clk), .D1 (\FIFO[2] [4]), .D2
       (data_in[4]), .S (n_171), .Q (\FIFO[2] [4]));
  DFMQM2RA \FIFO_reg[2][3] (.CK (clk), .D1 (\FIFO[2] [3]), .D2
       (data_in[3]), .S (n_171), .Q (\FIFO[2] [3]));
  DFMQM2RA \FIFO_reg[2][0] (.CK (clk), .D1 (\FIFO[2] [0]), .D2
       (data_in[0]), .S (n_171), .Q (\FIFO[2] [0]));
  AOI22M2R g7123__1666(.A1 (n_114), .A2 (\FIFO[0] [6]), .B1 (n_113),
       .B2 (\FIFO[1] [6]), .Z (n_109));
  AOI22M2R g7120__7410(.A1 (n_114), .A2 (\FIFO[0] [3]), .B1 (n_113),
       .B2 (\FIFO[1] [3]), .Z (n_108));
  AOI22M2R g7121__6417(.A1 (n_114), .A2 (\FIFO[0] [4]), .B1 (n_113),
       .B2 (\FIFO[1] [4]), .Z (n_107));
  AOI22M2R g7122__5477(.A1 (n_114), .A2 (\FIFO[0] [5]), .B1 (n_113),
       .B2 (\FIFO[1] [5]), .Z (n_106));
  NR2B1M2R g7099__2398(.B (n_118), .NA (\FIFO[3] [0]), .Z (n_105));
  NR2B1M2R g7097__5107(.B (n_118), .NA (\FIFO[3] [2]), .Z (n_104));
  NR2B1M2R g7124__6260(.B (n_118), .NA (\FIFO[3] [3]), .Z (n_103));
  NR2B1M2R g7098__4319(.B (n_118), .NA (\FIFO[3] [1]), .Z (n_102));
  DFMQM2RA \FIFO_reg[2][2] (.CK (clk), .D1 (\FIFO[2] [2]), .D2
       (data_in[2]), .S (n_171), .Q (\FIFO[2] [2]));
  DFMQM2RA \FIFO_reg[2][1] (.CK (clk), .D1 (\FIFO[2] [1]), .D2
       (data_in[1]), .S (n_171), .Q (\FIFO[2] [1]));
  DFMQM2RA \FIFO_reg[2][7] (.CK (clk), .D1 (\FIFO[2] [7]), .D2
       (data_in[7]), .S (n_171), .Q (\FIFO[2] [7]));
  DFMQM2RA \FIFO_reg[2][5] (.CK (clk), .D1 (\FIFO[2] [5]), .D2
       (data_in[5]), .S (n_171), .Q (\FIFO[2] [5]));
  DFQM8RA \count_reg[2] (.CK (clk), .D (n_88), .Q (count[2]));
  DFQM8RA \wr_pointer_reg[1] (.CK (clk), .D (n_83), .Q (wr_pointer[1]));
  ND2M2R g7144__8428(.A (n_81), .B (n_58), .Z (n_101));
  AOI31M8RA g7161__5526(.A1 (n_53), .A2 (n_84), .A3 (n_57), .B (n_3),
       .Z (n_128));
  ND2M12RA g7162__6783(.A (n_80), .B (n_5), .Z (n_118));
  AOI22M2R g7150__3680(.A1 (n_98), .A2 (data_in[4]), .B1
       (\data_out[4]_365 ), .B2 (n_97), .Z (n_100));
  AOI22M2R g7146__1617(.A1 (n_98), .A2 (data_in[0]), .B1
       (\data_out[0]_361 ), .B2 (n_97), .Z (n_99));
  AOI22M2R g7147__2802(.A1 (n_98), .A2 (data_in[1]), .B1
       (\data_out[1]_362 ), .B2 (n_97), .Z (n_96));
  AOI22M2R g7148__1705(.A1 (n_98), .A2 (data_in[2]), .B1
       (\data_out[2]_363 ), .B2 (n_97), .Z (n_95));
  AOI22M2R g7149__5122(.A1 (n_98), .A2 (data_in[3]), .B1
       (\data_out[3]_364 ), .B2 (n_97), .Z (n_94));
  OAI211M1R g7145__8246(.A1 (n_61), .A2 (n_63), .B (n_74), .C (n_36),
       .Z (n_93));
  AOI22M2R g7151__7098(.A1 (n_98), .A2 (data_in[5]), .B1
       (\data_out[5]_366 ), .B2 (n_97), .Z (n_92));
  AOI22M2R g7152__6131(.A1 (n_98), .A2 (data_in[6]), .B1
       (\data_out[6]_367 ), .B2 (n_97), .Z (n_91));
  AOI22M2R g7153__1881(.A1 (n_98), .A2 (data_in[7]), .B1
       (\data_out[7]_368 ), .B2 (n_97), .Z (n_90));
  OAI221M2R g7167__7482(.A1 (n_66), .A2 (n_33), .B1 (n_39), .B2 (n_73),
       .C (n_34), .Z (n_88));
  SDFQM1RA \FIFO_reg[3][0] (.CK (clk), .D (data_in[0]), .SD
       (\FIFO[3] [0]), .SE (n_87), .Q (\FIFO[3] [0]));
  SDFQM1RA \FIFO_reg[1][4] (.CK (clk), .D (data_in[4]), .SD
       (\FIFO[1] [4]), .SE (n_82), .Q (\FIFO[1] [4]));
  SDFQM1RA \FIFO_reg[0][7] (.CK (clk), .D (data_in[7]), .SD
       (\FIFO[0] [7]), .SE (n_86), .Q (\FIFO[0] [7]));
  SDFQM1RA \FIFO_reg[3][2] (.CK (clk), .D (data_in[2]), .SD
       (\FIFO[3] [2]), .SE (n_87), .Q (\FIFO[3] [2]));
  SDFQM1RA \FIFO_reg[0][2] (.CK (clk), .D (data_in[2]), .SD
       (\FIFO[0] [2]), .SE (n_86), .Q (\FIFO[0] [2]));
  SDFQM1RA \FIFO_reg[3][5] (.CK (clk), .D (data_in[5]), .SD
       (\FIFO[3] [5]), .SE (n_87), .Q (\FIFO[3] [5]));
  SDFQM8RA \rd_pointer_reg[0] (.CK (clk), .D (n_85), .SD (n_68), .SE
       (rd_pointer[0]), .Q (rd_pointer[0]));
  AOI21M6R g7164__4733(.A1 (n_46), .A2 (n_84), .B (n_9), .Z (n_113));
  NR2M8R g7165__6161(.A (n_6), .B (n_78), .Z (n_114));
  OAI21B20M2R g7168__9315(.B (n_82), .NA1 (n_77), .NA2 (wr_pointer[1]),
       .Z (n_83));
  SDFQM1RA \FIFO_reg[3][6] (.CK (clk), .D (data_in[6]), .SD
       (\FIFO[3] [6]), .SE (n_87), .Q (\FIFO[3] [6]));
  SDFQM1RA \FIFO_reg[1][2] (.CK (clk), .D (data_in[2]), .SD
       (\FIFO[1] [2]), .SE (n_82), .Q (\FIFO[1] [2]));
  SDFQM1RA \FIFO_reg[1][3] (.CK (clk), .D (data_in[3]), .SD
       (\FIFO[1] [3]), .SE (n_82), .Q (\FIFO[1] [3]));
  SDFQM1RA \FIFO_reg[1][6] (.CK (clk), .D (data_in[6]), .SD
       (\FIFO[1] [6]), .SE (n_82), .Q (\FIFO[1] [6]));
  SDFQM1RA \FIFO_reg[0][0] (.CK (clk), .D (data_in[0]), .SD
       (\FIFO[0] [0]), .SE (n_86), .Q (\FIFO[0] [0]));
  SDFQM1RA \FIFO_reg[0][4] (.CK (clk), .D (data_in[4]), .SD
       (\FIFO[0] [4]), .SE (n_86), .Q (\FIFO[0] [4]));
  SDFQM1RA \FIFO_reg[0][5] (.CK (clk), .D (data_in[5]), .SD
       (\FIFO[0] [5]), .SE (n_86), .Q (\FIFO[0] [5]));
  SDFQM1RA \FIFO_reg[0][3] (.CK (clk), .D (data_in[3]), .SD
       (\FIFO[0] [3]), .SE (n_86), .Q (\FIFO[0] [3]));
  SDFQM1RA \FIFO_reg[1][5] (.CK (clk), .D (data_in[5]), .SD
       (\FIFO[1] [5]), .SE (n_82), .Q (\FIFO[1] [5]));
  SDFQM1RA \FIFO_reg[1][0] (.CK (clk), .D (data_in[0]), .SD
       (\FIFO[1] [0]), .SE (n_82), .Q (\FIFO[1] [0]));
  SDFQM1RA \FIFO_reg[3][7] (.CK (clk), .D (data_in[7]), .SD
       (\FIFO[3] [7]), .SE (n_87), .Q (\FIFO[3] [7]));
  SDFQM1RA \FIFO_reg[3][4] (.CK (clk), .D (data_in[4]), .SD
       (\FIFO[3] [4]), .SE (n_87), .Q (\FIFO[3] [4]));
  SDFQM1RA \FIFO_reg[3][3] (.CK (clk), .D (data_in[3]), .SD
       (\FIFO[3] [3]), .SE (n_87), .Q (\FIFO[3] [3]));
  SDFQM1RA \FIFO_reg[0][1] (.CK (clk), .D (data_in[1]), .SD
       (\FIFO[0] [1]), .SE (n_86), .Q (\FIFO[0] [1]));
  SDFQM1RA \FIFO_reg[1][7] (.CK (clk), .D (data_in[7]), .SD
       (\FIFO[1] [7]), .SE (n_82), .Q (\FIFO[1] [7]));
  SDFQM1RA \FIFO_reg[1][1] (.CK (clk), .D (data_in[1]), .SD
       (\FIFO[1] [1]), .SE (n_82), .Q (\FIFO[1] [1]));
  SDFQM1RA \FIFO_reg[0][6] (.CK (clk), .D (data_in[6]), .SD
       (\FIFO[0] [6]), .SE (n_86), .Q (\FIFO[0] [6]));
  SDFQM1RA \FIFO_reg[3][1] (.CK (clk), .D (data_in[1]), .SD
       (\FIFO[3] [1]), .SE (n_87), .Q (\FIFO[3] [1]));
  DFQM8RA \wr_pointer_reg[0] (.CK (clk), .D (n_79), .Q (wr_pointer[0]));
  AOI32M2R g7170__9945(.A1 (n_144), .A2 (n_22), .A3 (count[2]), .B1
       (n_65), .B2 (n_154), .Z (n_81));
  OAI21B20M12RA g7163__2883(.B (n_84), .NA1 (n_161), .NA2 (n_151), .Z
       (n_80));
  OAI21M1R g7171__1666(.A1 (n_76), .A2 (n_75), .B (n_70), .Z (n_79));
  AOI21B20M4R g7176__7410(.B (n_67), .NA1 (n_59), .NA2 (n_54), .Z
       (n_78));
  OAI21B20M2R g7192__6417(.B (n_76), .NA1 (rst_n), .NA2 (n_75), .Z
       (n_77));
  MAOI22M2RA g7177__5477(.A1 (count[0]), .A2 (n_72), .B1 (n_73), .B2
       (n_51), .Z (n_74));
  OA21M8RA g7173__2398(.A1 (n_72), .A2 (n_31), .B (n_30), .Z (n_98));
  AOI21M1R g7169__5107(.A1 (n_12), .A2 (rst_n), .B (n_68), .Z (n_69));
  INVM10R g7184(.A (n_67), .Z (n_84));
  AOI22M2R g7187__6260(.A1 (n_26), .A2 (rst_n), .B1 (n_154), .B2
       (n_64), .Z (n_66));
  AO21M2RA g7189__4319(.A1 (count[0]), .A2 (n_64), .B (n_72), .Z
       (n_65));
  MAOI22M2RA g7190__8428(.A1 (n_23), .A2 (rd_en), .B1 (n_144), .B2
       (rd_en), .Z (n_63));
  OA21M12RA g7196__5526(.A1 (n_167), .A2 (n_24), .B (rd_en), .Z (n_67));
  OAI31M1R g7195__6783(.A1 (n_17), .A2 (n_61), .A3 (status_empty), .B
       (n_59), .Z (n_85));
  ND2B1M4R g7197__3680(.B (n_55), .NA (n_2), .Z (n_87));
  AOI221M1R g7175__1617(.A1 (n_15), .A2 (n_35), .B1 (n_47), .B2
       (rd_en), .C (n_21), .Z (n_58));
  ND2M2R g7180__2802(.A (n_151), .B (n_32), .Z (n_57));
  CKND2M2R g7181__1705(.A (n_55), .B (n_75), .Z (n_70));
  AO21M4RA g7172__5122(.A1 (n_16), .A2 (wr_en), .B (n_173), .Z (n_97));
  ND2M4R g7182__8246(.A (n_54), .B (n_55), .Z (n_86));
  CKND2M4R g7183__7098(.A (n_55), .B (n_45), .Z (n_82));
  OR2M2R g7186__6131(.A (n_59), .B (n_75), .Z (n_53));
  BUFTM2R g75__5115(.A (\data_out[5]_366 ), .E (\data_out[0]_369 ), .Z
       (data_out[5]));
  BUFTM2R g78__7482(.A (\data_out[2]_363 ), .E (\data_out[0]_369 ), .Z
       (data_out[2]));
  BUFTM2R g73__4733(.A (\data_out[7]_368 ), .E (\data_out[0]_369 ), .Z
       (data_out[7]));
  NR2M2R g7204__6161(.A (n_64), .B (n_47), .Z (n_76));
  OR2M2R g7185__9315(.A (n_59), .B (n_45), .Z (n_46));
  BUFTM2R g79__9945(.A (\data_out[1]_362 ), .E (\data_out[0]_369 ), .Z
       (data_out[1]));
  BUFTM2R g74__2883(.A (\data_out[6]_367 ), .E (\data_out[0]_369 ), .Z
       (data_out[6]));
  BUFTM2R g76__2346(.A (\data_out[4]_365 ), .E (\data_out[0]_369 ), .Z
       (data_out[4]));
  BUFTM2R g80__1666(.A (\data_out[0]_361 ), .E (\data_out[0]_369 ), .Z
       (data_out[0]));
  BUFTM2R g77__7410(.A (\data_out[3]_364 ), .E (\data_out[0]_369 ), .Z
       (data_out[3]));
  OAI221M2R g7178__6417(.A1 (n_61), .A2 (n_37), .B1 (n_28), .B2
       (n_151), .C (n_39), .Z (n_68));
  ND3M1R g7193__2398(.A (n_35), .B (n_144), .C (n_73), .Z (n_36));
  ND4M2R g7188__5107(.A (count[0]), .B (n_33), .C (n_154), .D (n_35),
       .Z (n_34));
  NR2M2R g7199__6260(.A (n_51), .B (wr_pointer[1]), .Z (n_32));
  NR2M2R g7203__4319(.A (n_51), .B (n_25), .Z (n_31));
  AOI221M6RA g7202__8428(.A1 (n_0), .A2 (rd_pointer[1]), .B1
       (wr_pointer[1]), .B2 (n_29), .C (n_13), .Z (n_30));
  NR2M1R g7205__5526(.A (count[2]), .B (n_51), .Z (n_72));
  NR2M6R g7200__6783(.A (n_28), .B (status_full), .Z (n_55));
  CKINVM2R g7215(.A (n_25), .Z (n_26));
  AOI21M4R g7210__3680(.A1 (n_157), .A2 (n_149), .B (n_61), .Z (n_24));
  CKND2M2R g7218__1617(.A (n_166), .B (n_20), .Z (n_23));
  ND2M4R g7206__2802(.A (n_56), .B (n_22), .Z (n_59));
  NR2M2R g7217__1705(.A (n_39), .B (n_20), .Z (n_21));
  NR2M1R g7209__5122(.A (count[2]), .B (n_20), .Z (half_full));
  BUFM2R g7216(.A (n_167), .Z (n_47));
  DFZRM2RA \data_out_reg[0]146 (.CK (clk), .D (n_64), .RB (n_17), .Q
       (UNCONNECTED), .QB (\data_out[0]_369 ));
  CKND2M2R g7198__8246(.A (n_151), .B (rd_en), .Z (n_16));
  INVM1R g7207(.A (n_37), .Z (status_empty));
  CKINVM1R g7208(.A (n_22), .Z (n_51));
  NR2M4R g7211__7098(.A (count[0]), .B (n_73), .Z (status_full));
  NR2M2R g7220__6131(.A (n_8), .B (n_15), .Z (n_25));
  OAI22M4R g7219__5115(.A1 (wr_pointer[0]), .A2 (n_12), .B1
       (rd_pointer[0]), .B2 (n_75), .Z (n_13));
  NR2M1R g7214__7482(.A (n_17), .B (n_28), .Z (n_22));
  ND3M4RA g7213__4733(.A (n_33), .B (n_144), .C (n_155), .Z (n_37));
  NR2M1R g7212__6161(.A (rd_en), .B (n_28), .Z (n_35));
  INVM2R g7233(.A (n_8), .Z (n_20));
  CKINVM1R g7224(.A (n_64), .Z (n_61));
  ND2M2R g7226__9945(.A (n_29), .B (n_12), .Z (n_6));
  NR2M2R g7227__2883(.A (n_12), .B (n_29), .Z (n_5));
  ND2M2R g7229__1666(.A (n_29), .B (rd_pointer[0]), .Z (n_9));
  NR2M2R g7240__7410(.A (count[0]), .B (n_157), .Z (n_8));
  NR2M1R g7232__6417(.A (wr_en), .B (n_1), .Z (n_64));
  ND2M2R g7235__5477(.A (n_12), .B (rd_pointer[1]), .Z (n_3));
  NR2M2R g7237__2398(.A (count[1]), .B (n_149), .Z (n_15));
  NR2M2R g7236__6260(.A (n_75), .B (wr_pointer[1]), .Z (n_45));
  ND2M1R g7239__4319(.A (n_17), .B (rst_n), .Z (n_39));
  ND2M3R g7241__8428(.A (n_157), .B (count[2]), .Z (n_73));
  ND3M4RA g7222__5526(.A (count[0]), .B (count[2]), .C (count[1]), .Z
       (n_56));
  ND2M1R g7231__6783(.A (wr_en), .B (rst_n), .Z (n_28));
  ND2M2R g7225__3680(.A (wr_pointer[1]), .B (wr_pointer[0]), .Z (n_2));
  NR2M2R g7230__1617(.A (wr_pointer[0]), .B (wr_pointer[1]), .Z (n_54));
  CKINVM1R g7246(.A (rst_n), .Z (n_1));
  INVM2R g7243(.A (wr_pointer[1]), .Z (n_0));
  CKINVM3R g7249(.A (count[2]), .Z (n_33));
  INVM2R g7248(.A (rd_pointer[0]), .Z (n_12));
  CKINVM1R g7244(.A (rd_en), .Z (n_17));
  CKINVM4R g7250(.A (wr_pointer[0]), .Z (n_75));
  CKINVM4R fopt4(.A (count[0]), .Z (n_144));
  BUFM6R fopt7299(.A (n_56), .Z (n_151));
  INVM2R fopt7300(.A (n_155), .Z (n_154));
  INVM12R fopt7302(.A (count[1]), .Z (n_157));
  AOI21M2R g2(.A1 (wr_pointer[1]), .A2 (wr_pointer[0]), .B (n_51), .Z
       (n_161));
  NR2M8R g19(.A (n_165), .B (n_166), .Z (n_167));
  ND2M8R g20(.A (n_157), .B (rst_n), .Z (n_165));
  ND2M6R g21(.A (n_149), .B (count[2]), .Z (n_166));
  DFM2RA \rd_pointer_reg[1] (.CK (clk), .D (n_172), .Q (rd_pointer[1]),
       .QB (n_29));
  DFM8RA \count_reg[0] (.CK (clk), .D (n_93), .Q (count[0]), .QB
       (n_149));
  DFM8RA \count_reg[1] (.CK (clk), .D (n_101), .Q (count[1]), .QB
       (n_155));
  ND2B1M8R g7318(.B (wr_pointer[1]), .NA (n_70), .Z (n_171));
  OAI22B10M2R g7319(.A1 (n_9), .B1 (n_69), .B2 (n_29), .NA2 (n_85), .Z
       (n_172));
  OAI31M2R g7320(.A1 (wr_en), .A2 (n_17), .A3 (n_37), .B (rst_n), .Z
       (n_173));
endmodule

